development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: message-me_development

production:
  adapter: redis
  url: <%= ENV['REDIS_TLS_URL'] %>
  channel_prefix: message-me_production
  ssl: true
  reconnect_attempts: 5